# Generated by Django 4.2.3 on 2023-07-17 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('content', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('Fasion', 'Fasion'), ('Travel', 'Travel'), ('Fitness', 'Fitness')], max_length=20)),
                ('tag', models.CharField(max_length=25)),
            ],
        ),
    ]
